### ISSUE TITLE
Issue with Frontend display on Magento CE 2.3.3

### ISSUE THREAD

**Issue by sodhancha** [khalti/khalti-magento#1]
The gateway renders fine on the backend even pulling transactions. However the Khalti payment option does not dislplay in the checkout page.

#Current Magento CE version: 
2.3.3

**Comment by manibibek** [comment]
This has been fixed now. Can you please test it from your end and let me know if it is working fine at your end. 

If it doesn't work at first try, please clear the compiled `.js` files from the `pub` folder and try generating the static content.

**Comment by manibibek** [comment]
Hi @sodhancha 

Please close this issue if the plugin is working fine at your end. 

Thank you
