### ISSUE TITLE
Magento CE 2.3.3 frontend button not rendering and is un-clickable

### ISSUE THREAD

**Issue by bijay135** [khalti/khalti-magento#2]
Hello, Khalti is now appearing in Payment Methods but the button has no caption and is completely un-clickable, thus it's not functioning from frontend.

I have tested this in two separate instances of Magento 2 using test mode.

Please look into this. Any support is appreciated. I have attached the screenshot of this issue below.
![Khalti Button Issue](https://user-images.githubusercontent.com/23445259/72499608-7044f180-385a-11ea-8147-cfada7f3a5a7.png)

**Comment by manibibek** [comment]
Hi @bijay135 , 

Can you try again the latest updated code? Please remove the compiled `js` from the `pub` folder and recompile the static content before trying. 

Thank you

**Comment by bijay135** [comment]
@manibibek Thank you for the quick support. After clearing the static files it renders flawlessly in fronted now.
